### PR TITLE
Rewrite resolver for opam packages to resolve from repository

### PR DESCRIPTION
**Pull request by andreypopp**
**WIP: DO NOT MERGE YET**

Previously we distributed pre-converted opam packages with esy. Now this PR makes `esy install` command to resolve opam packages directly from the repo.

Things left:
* [x] Add version resolution which relies on OCaml version
* [x] Support opam `patches`
* [x] Install from lockfile is broken

### CODE REVIEW

**Comment by andreypopp** [comment]
Added a more restrictive dependency resolution based on the OCaml compiler version declared in the top level package.

**Comment by andreypopp** [comment]
Alright, both `esy-ocaml-project` and `reason-cli` works with this setup. The only blocker for 4.04+ is this ocamlbuild [issue](https://github.com/ocaml/ocamlbuild/issues/69) (it's closed but not released yet).

**Comment by jordwalke** [comment]
> Support opam patches

Nice, did we support opam patches previously?

**Comment by andreypopp** [comment]
@jordwalke nope

**Comment by andreypopp** [comment]
Merging! Will fix remaining items in followups.

**Pull request merged**
